In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold

In [2]:
colnames = ["message", "Category"]
data = pd.read_csv("/Users/sarvani/Downloads/cancer_data.tsv", delimiter="\t", names=colnames)

In [3]:
messages = data["message"]
category = data["Category"]
categories= []
for i in category:
    if i == "no":
        categories.append(0)
    else:
        categories.append(1)
x_train,x_test,y_train,y_test=train_test_split(messages,categories,test_size=0.1)

In [15]:
print(x_train.shape[0])

1356


In [5]:
def create_unique_dict(text_arr):
    dictt = {}
    count = -1
    x = np.array(text_arr)
    text1 = (np.unique(x))

    for item in text1:
        data = (item.lower().strip().split(" "))
        for item1 in data:
            if item1 not in dictt:
                count = count +1
                dictt[item1] = count
    print((dictt))
    return dictt

In [6]:
def vectorize(text_arr,dictt):
    vectors  = []
    for sentence in text_arr:
        vector = [0] * len(dictt)
        words = (sentence.lower().strip().split(" "))
        for word in words:
            index = dictt[word]
            vector[index] += 1
        vectors.append(vector)
    print(np.array(vectors))
    return vectors

In [7]:
dictt = create_unique_dict(messages)

{'#armyhivestreamingparty': 0, 'is': 1, 'the': 2, 'purest': 3, 'thing': 4, "i've": 5, 'ever': 6, 'experienced.': 7, 'beyonce': 8, 'and': 9, 'bts': 10, 'together': 11, 'can': 12, 'cure': 13, 'cancer': 14, 'other': 15, 'diseases/illnesses': 16, 'bring': 17, 'world': 18, 'peace': 19, '💜💜💜💜': 20, '#ayurveda_a_panacea': 21, '': 22, '"mother': 23, 'of': 24, 'healing"': 25, 'st': 26, '@gurmeetramrahim': 27, 'ji': 28, 'tells': 29, 'that': 30, 'ayurveda': 31, 'first': 32, 'scientific': 33, 'medical': 34, 'branch': 35, 'originated': 36, 'in': 37, 'india.': 38, 'with': 39, 'yoga': 40, 'practices,': 41, 'it': 42, 'becomes': 43, 'a': 44, 'boon': 45, 'to': 46, 'cancer,': 47, 'kidney': 48, 'disorders,': 49, 'cardiac': 50, 'arrest,': 51, 'etc.': 52, 'https://t.co/7jdqksviqf': 53, "'mother": 54, "healing'.": 55, 'https://t.co/hrcikylyuz': 56, 'https://t.co/vkj1uq8sod': 57, '#executiveorder': 58, 'sick,': 59, 'deranged': 60, 'liberals': 61, "wouldn't": 62, 'be': 63, 'happy': 64, 'if': 65, 'president': 6

In [8]:
X = np.array(vectorize(messages, dictt))
Y = np.array(categories)

[[0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 1 3 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [9]:
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    clf = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(X_train, y_train)
    clf.predict(X_test)
    print(clf.score(X_test, y_test))
    print("blah blah blah")

TRAIN: [ 302  303  304 ... 1504 1505 1506] TEST: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 2

In [8]:
x = np.array(vectorize(x_train, dictt))
y = np.array(y_train)

[[0 3 4 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 2 4 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]]


In [9]:
x_test = np.array(vectorize(x_test, dictt))
y_test = np.array(y_test)

[[0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 [0 0 4 ... 0 0 0]]


In [10]:
clf = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(x, y)

In [11]:
clf.predict(x_test)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
clf.score(x_test, y_test)

0.8940397350993378

In [13]:
clf = SVC(gamma='auto')

In [14]:
clf.fit(x, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
print(clf.predict(x_test))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]


In [16]:
clf.score(x_test, y_test)

0.8675496688741722

In [17]:
clf = DecisionTreeClassifier(random_state=0)

In [18]:
clf.fit(x, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [19]:
print(clf.predict(x_test))

[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0]


In [20]:
clf.score(x_test, y_test)

0.8874172185430463

In [12]:
parameters = clf.coef_

In [14]:
print(parameters.shape)

(1, 13632)


In [16]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z)) 

In [17]:
def add_intercept(X):
    intercept = np.ones((X.shape[0], 1))
    return np.concatenate((intercept, X), axis=1)

In [18]:
def loss(h, y):
    return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()

In [20]:
def train(X,y, lr, num_iter):
    X = add_intercept(X)
    theta = np.zeros(X.shape[1])
    print(theta)

    for i in range(num_iter):
        z = np.dot(X, theta)
        h = sigmoid(z)
        gradient = np.dot(X.T, (h - y)) / y.size
        theta -= lr * gradient

        z = np.dot(X, theta)
        h = sigmoid(z)
        los = loss(h, y)
        print(los)
    return theta

In [21]:
def predict(X, theta):
    X = add_intercept(X)
    prob = sigmoid(np.dot(X, theta))
    return prob >= 0.5

In [22]:
def evaluate(test_x, test_y, theta):
        y_predicted = predict(test_x, theta)
        correct = 0
        for i,y in enumerate(test_y):
            if y == 0:
                y = False
            else:
                y = True
            if y == y_predicted[i]:
                correct = correct + 1
        total = y_predicted.size

        return (correct/total)*100

In [23]:
evaluate(x_test, y_test, train(x, y, 0.01, 5000))

[0. 0. 0. ... 0. 0. 0.]
0.6766328302060401
0.6612816885287294
0.6470067542569456
0.6337258870248259
0.6213621888002727
0.6098441395200428
0.5991055461882786
0.5890853644533068
0.5797274413614537
0.5709802152345791
0.5627963973375599
0.5551326514043678
0.5479492810491515
0.5412099310327533
0.5348813056995149
0.5289329061825053
0.5233367868735683
0.5180673309532754
0.5131010443366324
0.5084163671244438
0.503993501500266
0.4998142549411485
0.4958618975915476
0.4921210326665192
0.4885774787904075
0.4852181632321426
0.48203102506182016
0.479004927321104
0.4761295773690791
0.4733954546333663
0.4707937450621408
0.4683162816352437
0.4659554903512847
0.46370434116223025
0.46155630337735015
0.45950530510462534
0.45754569633991893
0.45567221535260716
0.45387995805116993
0.4521643500437176
0.4505211211368484
0.44894628204182757
0.44743610308012616
0.44598709470106773
0.4445959896429524
0.4432597265857296
0.44197543515830534
0.440740422177026
0.43955215900396966
0.43840826992452103
0.43730652145343

0.36434576769770366
0.3642480289822748
0.3641504225873276
0.3640529482040383
0.36395560552427736
0.36385839424060973
0.3637613140462964
0.3636643646352946
0.363567545702259
0.36347085694254283
0.3633742980521984
0.3632778687279785
0.36318156866733764
0.3630853975684325
0.36298935513012365
0.3628934410519764
0.3627976550342619
0.3627019967779587
0.36260646598475316
0.3625110623570414
0.36241578559793003
0.3623206354112374
0.3622256115014948
0.36213071357394755
0.3620359413345563
0.3619412944899981
0.36184677274766736
0.36175237581567693
0.36165810340285964
0.36156395521876883
0.36146993097367963
0.3613760303785898
0.36128225314522106
0.3611885989860197
0.3610950676141575
0.36100165874353274
0.36090837208877113
0.3608152073652266
0.3607221642889818
0.36062924257684903
0.36053644194637113
0.36044376211582196
0.3603512028042067
0.3602587637312631
0.3601664446174615
0.36007424518400555
0.35998216515283243
0.3598902042466136
0.3597983621887548
0.3597066387033966
0.35961503351541463
0.3595235

0.33169446483607884
0.3316331916498194
0.3315719721266092
0.3315108061648723
0.3314496936632825
0.33138863452076256
0.33132762863648374
0.33126667590986497
0.3312057762405726
0.3311449295285191
0.33108413567386313
0.3310233945770083
0.3309627061386031
0.3309020702595398
0.33084148684095427
0.33078095578422473
0.33072047699097185
0.33066005036305757
0.33059967580258476
0.3305393532118965
0.33047908249357555
0.33041886355044353
0.33035869628556047
0.33029858060222433
0.3302385164039701
0.3301785035945692
0.3301185420780291
0.3300586317585926
0.32999877254073723
0.32993896432917447
0.3298792070288493
0.3298195005449399
0.3297598447828564
0.3297002396482408
0.329640685046966
0.32958118088513555
0.32952172706908284
0.3294623235053706
0.3294029701007902
0.32934366676236115
0.3292844133973304
0.3292252099131719
0.329166056217586
0.3291069522184985
0.32904789782406074
0.32898889294264844
0.32892993748286126
0.32887103135352236
0.32881217446367766
0.3287533667225955
0.32869460803976547
0.328635

0.30942537833698225
0.30938024367090494
0.30933513549127684
0.30929005376036933
0.3092449984405343
0.309199969494204
0.30915496688389055
0.3091099905721859
0.30906504052176176
0.309020116695369
0.3089752190558381
0.30893034756607807
0.30888550218907695
0.30884068288790156
0.30879588962569676
0.30875112236568575
0.3087063810711697
0.3086616657055276
0.308616976232216
0.30857231261476875
0.3085276748167971
0.3084830628019889
0.30843847653410916
0.3083939159769992
0.30834938109457705
0.3083048718508365
0.3082603882098477
0.30821593013575627
0.3081714975927838
0.3081270905452269
0.30808270895745776
0.30803835279392333
0.3079940220191454
0.3079497165977205
0.30790543649431956
0.3078611816736877
0.3078169521006442
0.30777274774008206
0.3077285685569682
0.3076844145163426
0.307640285583319
0.307596181723084
0.30755210290089724
0.30750804908209095
0.30746402023207003
0.3074200163163116
0.3073760373003652
0.3073320831498521
0.3072881538304656
0.3072442493079704
0.30720036954820285
0.30715651451

0.29205631926844144
0.29201991849837383
0.29198353333424165
0.29194716375958263
0.291910809757963
0.2918744713129775
0.2918381484082492
0.29180184102742934
0.2917655491541977
0.291729272772262
0.29169301186535823
0.2916567664172504
0.2916205364117306
0.2915843218326185
0.29154812266376223
0.2915119388890373
0.291475770492347
0.2914396174576226
0.29140347976882275
0.29136735740993375
0.2913312503649694
0.29129515861797084
0.2912590821530069
0.2912230209541734
0.29118697500559365
0.2911509442914181
0.2911149287958243
0.29107892850301686
0.29104294339722775
0.2910069734627153
0.29097101868376535
0.2909350790446903
0.29089915452982923
0.2908632451235482
0.2908273508102399
0.2907914715743235
0.2907556074002449
0.29071975827247626
0.2906839241755164
0.29064810509389055
0.29061230101214997
0.2905765119148725
0.290540737786662
0.2905049786121487
0.29046923437598854
0.2904335050628639
0.290397790657483
0.29036209114457984
0.2903264065089144
0.2902907367352726
0.29025508180846593
0.2902194417133

0.2778460800536027
0.27781511062501346
0.27778415175436955
0.27775320343319
0.2777222656530057
0.2776913384053595
0.2776604216818063
0.2776295154739126
0.2775986197732568
0.2775677345714291
0.2775368598600315
0.2775059956306777
0.2774751418749932
0.2774442985846152
0.2774134657511926
0.27738264336638585
0.27735183142186726
0.2773210299093205
0.27729023882044107
0.2772594581469359
0.2772286878805236
0.2771979280129343
0.27716717853590944
0.27713643944120225
0.27710571072057716
0.2770749923658103
0.277044284368689
0.27701358672101223
0.27698289941459003
0.2769522224412441
0.27692155579280747
0.27689089946112416
0.2768602534380499
0.2768296177154514
0.27679899228520677
0.2767683771392053
0.27673777226934765
0.2767071776675454
0.2766765933257214
0.2766460192358099
0.2766154553897559
0.2765849017795157
0.2765543583970567
0.2765238252343574
0.27649330228340724
0.2764627895362067
0.2764322869847673
0.27640179462111153
0.276371312437273
0.2763408404252959
0.2763103785772356
0.27627992688515857

0.2655684933216484
0.26554136499739006
0.26551424447381955
0.26548713174598365
0.2654600268089344
0.2654329296577296
0.2654058402874328
0.26537875869311306
0.2653516848698451
0.26532461881270936
0.2652975605167915
0.2652705099771831
0.2652434671889812
0.26521643214728824
0.2651894048472126
0.2651623852838679
0.26513537345237326
0.26510836934785353
0.265081372965439
0.2650543843002654
0.26502740334747404
0.2650004301022117
0.2649734645596305
0.2649465067148884
0.2649195565631483
0.26489261409957915
0.2648656793193549
0.2648387522176549
0.26481183278966436
0.26478492103057355
0.26475801693557827
0.26473112049987974
0.26470423171868435
0.26467735058720426
0.2646504771006568
0.26462361125426465
0.26459675304325586
0.2645699024628638
0.26454305950832735
0.26451622417489046
0.2644893964578026
0.2644625763523186
0.2644357638536984
0.2644089589572073
0.26438216165811596
0.2643553719517004
0.26432858983324165
0.2643018152980262
0.26427504834134585
0.26424828895849745
0.2642215371447833
0.264194

0.254685523742995
0.2546613255779099
0.25463713352068496
0.2546129475681246
0.2545887677170361
0.25456459396422987
0.2545404263065191
0.25451626474072003
0.25449210926365184
0.2544679598721367
0.25444381656299975
0.2544196793330689
0.2543955481791753
0.2543714230981528
0.2543473040868382
0.25432319114207136
0.2542990842606949
0.25427498343955457
0.2542508886754989
0.2542267999653792
0.25420271730605004
0.25417864069436863
0.25415457012719506
0.2541305056013925
0.2541064471138269
0.25408239466136706
0.2540583482408848
0.2540343078492548
0.2540102734833544
0.25398624514006407
0.25396222281626707
0.2539382065088495
0.25391419621470024
0.2538901919307113
0.2538661936537772
0.25384220138079555
0.2538182151086667
0.25379423483429386
0.2537702605545832
0.2537462922664435
0.2537223299667865
0.25369837365252673
0.2536744233205817
0.25365047896787146
0.25362654059131906
0.25360260818785035
0.25357868175439385
0.2535547612878811
0.25353084678524634
0.2535069382434265
0.2534830356593614
0.25345913

0.24493645822283938
0.24491459596752913
0.24489273868801537
0.24487088638206875
0.24484903904746141
0.2448271966819675
0.24480535928336258
0.2447835268494242
0.24476169937793144
0.24473987686666512
0.24471805931340793
0.24469624671594412
0.24467443907205966
0.24465263637954227
0.24463083863618137
0.24460904583976809
0.24458725798809522
0.2445654750789573
0.24454369711015062
0.24452192407947299
0.24450015598472397
0.24447839282370495
0.24445663459421893
0.24443488129407054
0.24441313292106628
0.24439138947301392
0.24436965094772337
0.24434791734300598
0.24432618865667488
0.24430446488654484
0.2442827460304323
0.24426103208615527
0.2442393230515336
0.2442176189243887
0.2441959197025437
0.24417422538382344
0.24415253596605424
0.24413085144706426
0.24410917182468325
0.2440874970967426
0.24406582726107542
0.24404416231551643
0.24402250225790195
0.24400084708607
0.24397919679786031
0.24395755139111414
0.24393591086367447
0.24391427521338585
0.24389264443809455
0.2438710185356484
0.2438493975

0.236146858708319
0.23612691314046758
0.2361069717407711
0.23608703450757929
0.23606710143924295
0.2360471725341139
0.2360272477905451
0.23600732720689066
0.23598741078150562
0.23596749851274626
0.23594759039896973
0.2359276864385346
0.2359077866298001
0.23588789097112697
0.23586799946087667
0.23584811209741194
0.2358282288790965
0.23580834980429524
0.23578847487137408
0.2357686040787
0.235748737424641
0.23572887490756622
0.23570901652584592
0.23568916227785128
0.23566931216195464
0.23564946617652946
0.23562962431995016
0.23560978659059229
0.23558995298683236
0.23557012350704815
0.23555029814961828
0.2355304769129226
0.23551065979534183
0.23549084679525795
0.23547103791105395
0.2354512331411137
0.23543143248382237
0.235411635937566
0.2353918435007318
0.235372055171708
0.23535227094888378
0.23533249083064955
0.23531271481539667
0.23529294290151745
0.23527317508740547
0.23525341137145514
0.2352336517520621
0.2352138962276229
0.23519414479653514
0.23517439745719754
0.23515465420800977
0.2

0.2280625552676122
0.2280442378800328
0.228025924047716
0.22800761376939013
0.22798930704378426
0.22797100386962837
0.22795270424565298
0.22793440817058946
0.22791611564316977
0.2278978266621267
0.2278795412261938
0.22786125933410525
0.22784298098459607
0.22782470617640194
0.22780643490825925
0.22778816717890513
0.2277699029870775
0.22775164233151482
0.2277333852109565
0.2277151316241426
0.22769688156981394
0.22767863504671185
0.22766039205357855
0.2276421525891571
0.227623916652191
0.2276056842414247
0.22758745535560324
0.22756922999347243
0.22755100815377882
0.22753278983526964
0.2275145750366928
0.22749636375679705
0.2274781559943317
0.22745995174804684
0.22744175101669337
0.22742355379902274
0.2274053600937872
0.22738716989973973
0.22736898321563398
0.22735080004022432
0.22733262037226593
0.2273144442105144
0.22729627155372642
0.2272781024006591
0.2272599367500704
0.22724177460071895
0.2272236159513641
0.22720546080076584
0.227187309147685
0.22716916099088294
0.22715101632912182
0.

0.22061659007050394
0.22059967148226514
0.22058275596972893
0.22056584353188521
0.22054893416772425
0.22053202787623702
0.22051512465641493
0.22049822450724985
0.22048132742773432
0.22046443341686123
0.2204475424736241
0.220430654597017
0.22041376978603433
0.22039688803967122
0.22038000935692317
0.22036313373678626
0.2203462611782571
0.22032939168033275
0.2203125252420108
0.22029566186228952
0.22027880154016738
0.22026194427464352
0.22024509006471782
0.22022823890939025
0.2202113908076616
0.220194545758533
0.2201777037610063
0.2201608648140836
0.22014402891676765
0.22012719606806172
0.22011036626696956
0.22009353951249544
0.22007671580364413
0.2200598951394209
0.22004307751883154
0.22002626294088234
0.22000945140458014
0.21999264290893228
0.21997583745294652
0.21995903503563122
0.2199422356559951
0.21992543931304764
0.21990864600579868
0.21989185573325845
0.21987506849443783
0.21985828428834833
0.21984150311400164
0.21982472497041014
0.21980794985658675
0.21979117777154486
0.2197744087

90.72847682119205