In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold

In [9]:
data = pd.read_csv("/Users/sarvani/Downloads/yelp.csv")

In [6]:
print(data['text'][0])

My wife took me here on my birthday for breakfast and it was excellent.  The weather was perfect which made sitting outside overlooking their grounds an absolute pleasure.  Our waitress was excellent and our food arrived quickly on the semi-busy Saturday morning.  It looked like the place fills up pretty quickly so the earlier you get here the better.

Do yourself a favor and get their Bloody Mary.  It was phenomenal and simply the best I've ever had.  I'm pretty sure they only use ingredients from their garden and blend them fresh when you order it.  It was amazing.

While EVERYTHING on the menu looks excellent, I had the white truffle scrambled eggs vegetable skillet and it was tasty and delicious.  It came with 2 pieces of their griddled bread with was amazing and it absolutely made the meal complete.  It was the best "toast" I've ever had.

Anyway, I can't wait to go back!


In [10]:
reviews = data["text"]
funny_votes = data["funny"]

In [11]:
votes = []
cnt1=0
cnt2=0
for i in funny_votes:
    if i > 2:
        votes.append(1)
        cnt1 = cnt1 + 1
    else:
        votes.append(0)
        cnt2 = cnt2 + 1
print(cnt1)
print(' ')
print(cnt2)

752
 
9248


In [12]:
x_train,x_test,y_train,y_test=train_test_split(reviews,votes,test_size=0.1)

In [13]:
print(x_test.shape)

(1000,)


In [14]:
def create_unique_dict(text_arr):
    dictt = {}
    count = -1
    x = np.array(text_arr)
    text1 = (np.unique(x))

    for item in text1:
        data = (item.lower().strip().split(" "))
        for item1 in data:
            if item1 not in dictt:
                count = count +1
                dictt[item1] = count
    print((dictt))
    return dictt

In [15]:
def vectorize(text_arr,dictt):
    vectors  = []
    for sentence in text_arr:
        vector = [0] * len(dictt)
        words = (sentence.lower().strip().split(" "))
        for word in words:
            index = dictt[word]
            vector[index] += 1
        vectors.append(vector)
    print(np.array(vectors))
    return vectors

In [16]:
dictt = create_unique_dict(reviews)

{'!!!!!!!': 0, '***': 1, '': 2, 'o': 3, 'm': 4, 'g': 5, '......so': 6, 'good': 7, '!!!!!!!\n\nmy': 8, 'family': 9, '&': 10, 'i': 11, 'keep': 12, 'coming': 13, 'back': 14, 'to': 15, 'this': 16, 'place.': 17, 'we': 18, 'drive': 19, 'over': 20, '10': 21, 'miles': 22, 'get': 23, 'our': 24, 'fix.': 25, 'think': 26, "it's": 27, 'safe': 28, 'say': 29, 'that': 30, 'are': 31, 'officially': 32, 'hooked,': 33, 'and': 34, 'when': 35, 'jonesin': 36, 'for': 37, 'tacos': 38, 'atoyac': 39, 'there': 40, 'better': 41, 'not': 42, 'be': 43, 'anyone': 44, 'or': 45, 'anything': 46, 'standing': 47, 'between': 48, 'us': 49, 'food!\n\ntoday': 50, 'all': 51, 'came': 52, 'aways': 53, 'lickin': 54, 'chops': 55, 'yummy': 56, 'in': 57, 'tummy.': 58, 'might': 59, 'brush': 60, 'my': 61, 'teeth': 62, "tonight!\n\nhere's": 63, 'what': 64, 'had:\n\n~': 65, 'had': 66, 'scrambled': 67, 'eggs': 68, 'with': 69, 'chorizo': 70, '(dry),': 71, 'cheese,': 72, 'onions,': 73, 'potatoes,': 74, 'jalapenos.': 75, 'served': 76, 'side'

In [8]:
X = np.array(vectorize(reviews, dictt))
Y = np.array(votes)

[[0 0 8 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 8 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]
    clf = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(X_train, y_train)
    clf.predict(X_test)
    print(clf.score(X_test, y_test))
    print("blah blah blah")

TRAIN: [2000 2001 2002 ... 9997 9998 9999] TEST: [   0    1    2 ... 1997 1998 1999]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.921
blah blah blah
TRAIN: [   0    1    2 ... 9997 9998 9999] TEST: [2000 2001 2002 ... 3997 3998 3999]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.9215
blah blah blah
TRAIN: [   0    1    2 ... 9997 9998 9999] TEST: [4000 4001 4002 ... 5997 5998 5999]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.911
blah blah blah
TRAIN: [   0    1    2 ... 9997 9998 9999] TEST: [6000 6001 6002 ... 7997 7998 7999]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.905
blah blah blah
TRAIN: [   0    1    2 ... 7997 7998 7999] TEST: [8000 8001 8002 ... 9997 9998 9999]


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.9245
blah blah blah


In [17]:
x = np.array(vectorize(x_train, dictt))
y = np.array(y_train)

[[ 0  0  7 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0 30 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]]


In [18]:
x_test = np.array(vectorize(x_test, dictt))
y_test = np.array(y_test)

[[ 0  0  1 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  8 ...  0  0  0]
 ...
 [ 0  0 17 ...  0  0  0]
 [ 0  0  1 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [21]:
clf = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(x, y)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


In [22]:
clf.predict(x_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [23]:
clf.score(x_test, y_test)

0.92

In [13]:
clf = SVC(gamma='auto')

In [14]:
clf.fit(x, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
print(clf.predict(x_test))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [16]:
clf.score(x_test, y_test)

0.922

In [17]:
clf = DecisionTreeClassifier(random_state=0)

In [18]:
clf.fit(x, y) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [ ]:
clf.score(x_test, y_test)

In [19]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z)) 

In [20]:
def add_intercept(X):
    intercept = np.ones((X.shape[0], 1))
    return np.concatenate((intercept, X), axis=1)

In [21]:
def loss(h, y):
    return (-y * np.log(h) - (1 - y) * np.log(1 - h)).mean()

In [22]:
def train(X,y, lr, num_iter):
    X = add_intercept(X)
    theta = np.zeros(X.shape[1])
    print(theta)

    for i in range(num_iter):
        z = np.dot(X, theta)
        h = sigmoid(z)
        gradient = np.dot(X.T, (h - y)) / y.size
        theta -= lr * gradient

        z = np.dot(X, theta)
        h = sigmoid(z)
        los = loss(h, y)
        print(los)
    return theta

In [23]:
def predict(X, theta):
    X = add_intercept(X)
    prob = sigmoid(np.dot(X, theta))
    return prob >= 0.5

In [24]:
def evaluate(test_x, test_y, theta):
        y_predicted = predict(test_x, theta)
        correct = 0
        for i,y in enumerate(test_y):
            if y == 0:
                y = False
            else:
                y = True
            if y == y_predicted[i]:
                correct = correct + 1
        total = y_predicted.size

        return (correct/total)*100

In [ ]:
evaluate(x_test, y_test, train(x, y, 0.01, 5000))

[0. 0. 0. ... 0. 0. 0.]
0.5492566212933008
0.5121231821630017
0.49510301146414554
0.4855891264386319
0.4796608954818037
0.4756835642016511
0.47285773866231656
0.4707506383700711
0.469110767745017
0.46778417728311644
0.4666728199526439
0.4657122852612956
0.4648591991566515
0.4640837612863941
0.4633651569751656
0.46268864776075214
0.46204367770748234
0.4614226133620271
0.46081988939812646
0.4602314199067549
0.4596541870586455
0.4590859502309049
0.45852503817401086
0.4579701991725156
0.4574204921730057
0.45687520714346264
0.4563338064745468
0.45579588164508045
0.4552611210356094
0.4547292859321831
0.45420019257846284
0.4536736987145568
0.4531496934572159
0.4526280896768547
0.45210881824577986
0.45159182369229584
0.4510770609133347
0.45056449268553356
0.45005408777949746
0.4495458195303185
0.44903966475356527
0.4485356029230754
0.4480336155472712
0.4475336856960835
0.44703579764216894
0.4465399365888746
0.44604608846404525
0.44555423976380076
0.4450643774342271
0.4445764887818252
0.4440905

0.34091886487815537
0.34075995279160126
0.34060139532387895
0.3404431911670525
0.3402853390191629
0.3401278375841985
0.3399706855720651
0.33981388169855625
0.33965742468532406
0.33950131325984995
0.339345546155416
0.3391901221110757
0.33903503987162575
0.33888029818757753
0.33872589581512885
0.3385718315161362
0.3384181040580866
0.33826471221407034
0.33811165476275323
0.3379589304883491
0.3378065381805934
0.33765447663471576
0.3375027446514132
0.3373513410368237
0.3372002646024998
0.3370495141653823
0.336899088547774
0.3367489865773141
0.33659920708695207
0.3364497489149223
0.3363006109047185
0.33615179190506833
0.3360032907699086
0.3358551063583597
0.3357072375347013
0.33555968316834706
0.33541244213382077
0.3352655133107313
0.3351188955837487
0.3349725878425797
0.33482658898194434
0.33468089790155137
0.33453551350607463
0.33439043470513036
0.3342456604132524
0.33410118954986956
0.3339570210392828
0.3338131538106412
0.3336695867979197
0.3335263189398959
0.3333833491801278
0.3332406764